# This is necessary to generate default.apspec if you didn't
# './configure' GNU FreeDink yet - which is usually the case if you
# just want to build the package. If you already ran './configure',
# then 'makepackage' will automatically use config.status to
# regenerate default.apspec.

VERSION=$(shell grep AC_INIT ../configure.ac | grep -o -E '[0-9]+(\.[0-9]+)+')
quick-configure:
	sed -e 's/@VERSION@/$(VERSION)/' default.apspec.in > default.apspec
